var Move = require('./Prototypes.js').Move

var Flame_Thrower = new Move('Flame Thrower', 50)
var Ember = new Move('Ember', 20)
var Fly = new Move('Fly', 40)
var Dragon_Claw = new Move('Dragon Claw', 60)
var Water_Gun = new Move('Water Gun', 50)
var Hydro_Pump = new Move('Hydro Pump', 60)
var Water_pulse = new Move('Water Pulse', 40)
var Bubble = new Move('Bubble', 20)
var Razor_Leaf = new Move('Razor Leaf', 40)
var Vine_Whip = new Move('Vine Whip', 50)
var Leech_Seed = new Move('Leech Seed', 10, true)
var Solar_Beam = new Move('Solar Beam', 60)
var Scratch = new Move('Scratch', 30)
var Tail_Whip = new Move('Tail Whip',20)
var Confusion = new Move('Confusion', 60)
var Hypnosis = new Move('Hypnosis', 30)
var Mean_Look = new Move('Mean Look', 20)
var Payback = new Move('Payback', 40)
var Shadow_Ball = new Move('Shadow Ball', 60)
var Aqua_Tail = new Move('Aqua Tail', 30)
var Crunch = new Move('Crunch', 50)
var Hyper_Beam = new Move('Hyper Beam', 60)
var Pound = new Move('Pound', 40)
var Takedown = new Move('Takedown', 60)
var Tail_Whip = new Move('Tail Whip', 30)
var Quick_Attack = new Move('Quick Attack', 50)
var Thunder = new Move('Thunder', 40)
var Thunder_Bolt = new Move('Thunder_Bolt', 60)
var Confusion_Array = new Move('Confusion Array', 40)
var Sing = new Move('Sing', 50)
var Gyro_Ball = new Move('Gyro Ball', 40)
var Hyper_Voice = new Move('Hyper Voice', 60)
var Acid = new Move('Acid', 30)
var Absorb = new Move('Absorb', 50)
var Toxic = new Move('Toxic', 40)
var Giga_Drain = new Move('Giga Drain', 60)
var Telekinesis = new Move('Telekinesis', 50)
var Psychic = new Move('Psychic', 40)
var Psybeam = new Move('Psybeam', 60)


exports.Charizard = [Flame_Thrower, Ember, Fly, Dragon_Claw]
exports.Venusaur = [Razor_Leaf, Vine_Whip, Leech_Seed, Solar_Beam]
exports.Blastoise = [Water_Gun, Hydro_Pump, Water_pulse, Bubble]
exports.Psyduck = [Scratch, Tail_Whip, Water_Gun, Confusion]
exports.Gastly = [Hypnosis, Mean_Look, Payback, Shadow_Ball]
exports.Gyarados = [Aqua_Tail, Crunch, Hydro_Pump, Hyper_Beam]
exports.Snorlax = [Razor_Leaf, Vine_Whip, Pound, Takedown]
exports.Pikachu = [Tail_Whip, Quick_Attack, Thunder, Thunder_Bolt]
exports.Ninetales = [Flame_Thrower, Quick_Attack, Confusion_Array, Ember]
exports.Jigglypuff = [Pound, Sing, Gyro_Ball, Hyper_Voice]
exports.Gloom = [Acid, Absorb, Toxic, Giga_Drain]
exports.Alakazam = [Confusion, Telekinesis, Psychic, Psybeam]
